/// This code was generated by
/// \ / _    _  _|   _  _
///  | (_)\/(_)(_|\/| |(/_  v1.0.0
///       /       /

using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Xml.Linq;
using Twilio.Types;

namespace Twilio.TwiML.Voice 
{

    /// <summary>
    /// Reject TwiML Verb
    /// </summary>
    public class Reject : TwiML 
    {
        public sealed class ReasonEnum : StringEnum 
        {
            private ReasonEnum(string value) : base(value) {}
            public ReasonEnum() {}

            public static readonly ReasonEnum Rejected = new ReasonEnum("rejected");
            public static readonly ReasonEnum Busy = new ReasonEnum("busy");
        }

        /// <summary>
        /// Rejection reason
        /// </summary>
        public Reject.ReasonEnum Reason { get; set; }

        /// <summary>
        /// Create a new Reject
        /// </summary>
        /// <param name="reason"> Rejection reason </param>
        public Reject(Reject.ReasonEnum reason = null) : base("Reject")
        {
            this.Reason = reason;
        }

        /// <summary>
        /// Return the body of the TwiML tag
        /// </summary>
        protected override string GetElementBody()
        {
            return null;
        }

        /// <summary>
        /// Return the attributes of the TwiML tag
        /// </summary>
        protected override List<XAttribute> GetElementAttributes()
        {
            var attributes = new List<XAttribute>();
            if (this.Reason != null)
            {
                attributes.Add(new XAttribute("reason", this.Reason.ToString()));
            }
            return attributes;
        }
    }

}