/// This code was generated by
/// \ / _    _  _|   _  _
///  | (_)\/(_)(_|\/| |(/_  v1.0.0
///       /       /

using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Xml.Linq;

namespace Twilio.TwiML.Voice 
{

    /// <summary>
    /// Sim TwiML Noun
    /// </summary>
    public class Sim : TwiML 
    {
        /// <summary>
        /// SIM SID
        /// </summary>
        public string SimSid { get; set; }

        /// <summary>
        /// Create a new Sim
        /// </summary>
        /// <param name="simSid"> SIM SID, the body of the TwiML Element. </param>
        public Sim(string simSid = null) : base("Sim")
        {
            this.SimSid = simSid;
        }

        /// <summary>
        /// Return the body of the TwiML tag
        /// </summary>
        protected override string GetElementBody()
        {
            return this.SimSid.ToString();
        }

        /// <summary>
        /// Return the attributes of the TwiML tag
        /// </summary>
        protected override List<XAttribute> GetElementAttributes()
        {
            var attributes = new List<XAttribute>();
            return attributes;
        }
    }

}