/// This code was generated by
/// \ / _    _  _|   _  _
///  | (_)\/(_)(_|\/| |(/_  v1.0.0
///       /       /

using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Xml.Linq;

namespace Twilio.TwiML.Messaging 
{

    /// <summary>
    /// Body TwiML Noun
    /// </summary>
    public class Body : TwiML 
    {
        /// <summary>
        /// Message Body
        /// </summary>
        public string Message { get; set; }

        /// <summary>
        /// Create a new Body
        /// </summary>
        /// <param name="message"> Message Body, the body of the TwiML Element. </param>
        public Body(string message = null) : base("Body")
        {
            this.Message = message;
        }

        /// <summary>
        /// Return the body of the TwiML tag
        /// </summary>
        protected override string GetElementBody()
        {
            return this.Message;
        }

        /// <summary>
        /// Return the attributes of the TwiML tag
        /// </summary>
        protected override List<XAttribute> GetElementAttributes()
        {
            var attributes = new List<XAttribute>();
            return attributes;
        }
    }

}