/// This code was generated by
/// \ / _    _  _|   _  _
///  | (_)\/(_)(_|\/| |(/_  v1.0.0
///       /       /

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Xml.Linq;

namespace Twilio.TwiML.Messaging 
{

    /// <summary>
    /// Media TwiML Noun
    /// </summary>
    public class Media : TwiML 
    {
        /// <summary>
        /// Media URL
        /// </summary>
        public Uri Url { get; set; }

        /// <summary>
        /// Create a new Media
        /// </summary>
        /// <param name="url"> Media URL, the body of the TwiML Element. </param>
        public Media(Uri url = null) : base("Media")
        {
            this.Url = url;
        }

        /// <summary>
        /// Return the body of the TwiML tag
        /// </summary>
        protected override string GetElementBody()
        {
            return this.Url.AbsoluteUri;
        }

        /// <summary>
        /// Return the attributes of the TwiML tag
        /// </summary>
        protected override List<XAttribute> GetElementAttributes()
        {
            var attributes = new List<XAttribute>();
            return attributes;
        }
    }

}