/// This code was generated by
/// \ / _    _  _|   _  _
///  | (_)\/(_)(_|\/| |(/_  v1.0.0
///       /       /

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Xml.Linq;
using Twilio.TwiML.Messaging;

namespace Twilio.TwiML.Messaging 
{

    /// <summary>
    /// Message TwiML Verb
    /// </summary>
    public class Message : TwiML 
    {
        /// <summary>
        /// Message Body
        /// </summary>
        public string Body { get; set; }
        /// <summary>
        /// Phone Number to send Message to
        /// </summary>
        public string To { get; set; }
        /// <summary>
        /// Phone Number to send Message from
        /// </summary>
        public string From { get; set; }
        /// <summary>
        /// Action URL
        /// </summary>
        public Uri Action { get; set; }
        /// <summary>
        /// Action URL Method
        /// </summary>
        public Twilio.Http.HttpMethod Method { get; set; }

        /// <summary>
        /// Create a new Message
        /// </summary>
        /// <param name="body"> Message Body, the body of the TwiML Element. </param>
        /// <param name="to"> Phone Number to send Message to. Also accepts stringified Types.PhoneNumber </param>
        /// <param name="from"> Phone Number to send Message from. Also accepts stringified Types.PhoneNumber </param>
        /// <param name="action"> Action URL </param>
        /// <param name="method"> Action URL Method </param>
        public Message(string body = null, string to = null, string from = null, Uri action = null, Twilio.Http.HttpMethod method = null) : base("Message")
        {
            this.Body = body;
            this.To = to;
            this.From = from;
            this.Action = action;
            this.Method = method;
        }

        /// <summary>
        /// Return the body of the TwiML tag
        /// </summary>
        protected override string GetElementBody()
        {
            return this.Body;
        }

        /// <summary>
        /// Return the attributes of the TwiML tag
        /// </summary>
        protected override List<XAttribute> GetElementAttributes()
        {
            var attributes = new List<XAttribute>();
            if (this.To != null)
            {
                attributes.Add(new XAttribute("to", this.To));
            }
            if (this.From != null)
            {
                attributes.Add(new XAttribute("from", this.From));
            }
            if (this.Action != null)
            {
                attributes.Add(new XAttribute("action", this.Action.AbsoluteUri));
            }
            if (this.Method != null)
            {
                attributes.Add(new XAttribute("method", this.Method.ToString()));
            }
            return attributes;
        }

        /// <summary>
        /// Create a new <Message/> element and append it as a child of this element.
        /// </summary>
        /// <param name="message"> Message Body, the body of the TwiML Element. </param>
        public Message BodyElement(string message = null)
        {
            var newChild = new Body(message);
            this.Append(newChild);
            return this;
        }

        /// <summary>
        /// Create a new <Message/> element and append it as a child of this element.
        /// </summary>
        /// <param name="url"> Media URL, the body of the TwiML Element. </param>
        public Message Media(Uri url = null)
        {
            var newChild = new Media(url);
            this.Append(newChild);
            return this;
        }
    }

}