/// This code was generated by
/// \ / _    _  _|   _  _
///  | (_)\/(_)(_|\/| |(/_  v1.0.0
///       /       /

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Xml.Linq;

namespace Twilio.TwiML.Messaging 
{

    /// <summary>
    /// Redirect TwiML Verb
    /// </summary>
    public class Redirect : TwiML 
    {
        /// <summary>
        /// Redirect URL
        /// </summary>
        public Uri Url { get; set; }
        /// <summary>
        /// Redirect URL method
        /// </summary>
        public Twilio.Http.HttpMethod Method { get; set; }

        /// <summary>
        /// Create a new Redirect
        /// </summary>
        /// <param name="url"> Redirect URL, the body of the TwiML Element. </param>
        /// <param name="method"> Redirect URL method </param>
        public Redirect(Uri url = null, Twilio.Http.HttpMethod method = null) : base("Redirect")
        {
            this.Url = url;
            this.Method = method;
        }

        /// <summary>
        /// Return the body of the TwiML tag
        /// </summary>
        protected override string GetElementBody()
        {
            return this.Url.AbsoluteUri;
        }

        /// <summary>
        /// Return the attributes of the TwiML tag
        /// </summary>
        protected override List<XAttribute> GetElementAttributes()
        {
            var attributes = new List<XAttribute>();
            if (this.Method != null)
            {
                attributes.Add(new XAttribute("method", this.Method.ToString()));
            }
            return attributes;
        }
    }

}