/// This code was generated by
/// \ / _    _  _|   _  _
///  | (_)\/(_)(_|\/| |(/_  v1.0.0
///       /       /

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Xml.Linq;
using Twilio.TwiML.Fax;

namespace Twilio.TwiML 
{

    /// <summary>
    /// Response TwiML for Faxes
    /// </summary>
    public class FaxResponse : TwiML 
    {
        /// <summary>
        /// Create a new FaxResponse
        /// </summary>
        public FaxResponse() : base("Response")
        {
        }

        /// <summary>
        /// Return the body of the TwiML tag
        /// </summary>
        protected override string GetElementBody()
        {
            return null;
        }

        /// <summary>
        /// Return the attributes of the TwiML tag
        /// </summary>
        protected override List<XAttribute> GetElementAttributes()
        {
            var attributes = new List<XAttribute>();
            return attributes;
        }

        /// <summary>
        /// Create a new <Response/> element and append it as a child of this element.
        /// </summary>
        /// <param name="action"> Receive action URL </param>
        /// <param name="method"> Receive action URL method </param>
        public FaxResponse Receive(Uri action = null, Twilio.Http.HttpMethod method = null)
        {
            var newChild = new Receive(action, method);
            this.Append(newChild);
            return this;
        }
    }

}