/// This code was generated by
/// \ / _    _  _|   _  _
///  | (_)\/(_)(_|\/| |(/_  v1.0.0
///       /       /

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Xml.Linq;
using Twilio.TwiML.Messaging;

namespace Twilio.TwiML 
{

    /// <summary>
    /// Response TwiML for Messages
    /// </summary>
    public class MessagingResponse : TwiML 
    {
        /// <summary>
        /// Create a new MessagingResponse
        /// </summary>
        public MessagingResponse() : base("Response")
        {
        }

        /// <summary>
        /// Return the body of the TwiML tag
        /// </summary>
        protected override string GetElementBody()
        {
            return null;
        }

        /// <summary>
        /// Return the attributes of the TwiML tag
        /// </summary>
        protected override List<XAttribute> GetElementAttributes()
        {
            var attributes = new List<XAttribute>();
            return attributes;
        }

        /// <summary>
        /// Create a new <Response/> element and append it as a child of this element.
        /// </summary>
        /// <param name="body"> Message Body, the body of the TwiML Element. </param>
        /// <param name="to"> Phone Number to send Message to. Also accepts stringified Types.PhoneNumber </param>
        /// <param name="from"> Phone Number to send Message from. Also accepts stringified Types.PhoneNumber </param>
        /// <param name="action"> Action URL </param>
        /// <param name="method"> Action URL Method </param>
        public MessagingResponse Message(string body = null, string to = null, string from = null, Uri action = null, Twilio.Http.HttpMethod method = null)
        {
            var newChild = new Message(body, to, from, action, method);
            this.Append(newChild);
            return this;
        }

        /// <summary>
        /// Create a new <Response/> element and append it as a child of this element.
        /// </summary>
        /// <param name="url"> Redirect URL, the body of the TwiML Element. </param>
        /// <param name="method"> Redirect URL method </param>
        public MessagingResponse Redirect(Uri url = null, Twilio.Http.HttpMethod method = null)
        {
            var newChild = new Redirect(url, method);
            this.Append(newChild);
            return this;
        }
    }

}